# Generated by Django 5.0.1 on 2024-01-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordmodel",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
