# Generated by Django 5.0 on 2023-12-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=40)),
                ("category", models.CharField(max_length=40)),
                ("sub_category", models.CharField(max_length=40)),
                ("payment", models.CharField(max_length=40)),
                ("amount", models.FloatField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name="expense",
            name="budget",
        ),
        migrations.DeleteModel(
            name="Balance",
        ),
        migrations.DeleteModel(
            name="Budget",
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
    ]
