# Generated by Django 5.0.1 on 2024-01-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_alter_recordmodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordmodel",
            name="category",
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name="recordmodel",
            name="sub_category",
            field=models.CharField(default=None, max_length=40),
        ),
    ]
