<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-01-20 08:32
=======
# Generated by Django 5.0 on 2023-12-30 07:57
>>>>>>> cb355fdb365b6ebb28770a53de2173929ea08a18

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    dependencies = [
        ("wallet", "0003_recordmodel_remove_expense_budget_delete_balance_and_more"),
=======

    dependencies = [
        ('wallet', '0003_recordmodel_remove_expense_budget_delete_balance_and_more'),
>>>>>>> cb355fdb365b6ebb28770a53de2173929ea08a18
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="recordmodel",
            name="time",
=======
            model_name='recordmodel',
            name='time',
>>>>>>> cb355fdb365b6ebb28770a53de2173929ea08a18
            field=models.TimeField(auto_now_add=True),
        ),
    ]
