name: Schedule for GET requests

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  keep-it-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep WebApp alive
        run: |
          for i in {1..3}
          do
            echo "Execute first GET requests"
            response=$(curl -sS https://personal-wallet.onrender.com/)
            echo "Wait 300 seconds"
            sleep 300
            echo "GET Request operation was successful"
          done
